[project]
name = "lexisynapseai"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "flet==0.27.6",
    "openai>=1.82.0",
    "pip>=25.1.1",
    "python-dotenv>=1.1.0",
]
